# =========================
# Server
# =========================
server.port=${SERVER_PORT:8080}
spring.application.name=ewm-main-server

# =========================
# Datasource
# =========================
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:ewm_main}
spring.datasource.username=${DB_USER:ewm}
spring.datasource.password=${DB_PASSWORD:ewm}

# =========================
# JPA / Hibernate
# =========================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.jpa.show-sql=false

# =========================
# Liquibase
# =========================
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db.changelog/db.changelog-master.yaml

# =========================
# JSON / DateTime
# =========================
spring.jackson.serialization.write-dates-as-timestamps=false

spring.mvc.format.date-time=yyyy-MM-dd HH:mm:ss
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss

# =========================
# Stats service (Feign base URL)
# =========================
ewm.stats.url=${STATS_SERVER_URL:http://localhost:9091}

# ???????? Feign
spring.cloud.openfeign.client.config.default.connectTimeout=${FEIGN_CONNECT_TIMEOUT_MS:3000}
spring.cloud.openfeign.client.config.default.readTimeout=${FEIGN_READ_TIMEOUT_MS:5000}

# =========================
# Logging
# =========================
logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.type.descriptor.sql=OFF